language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - 0.6
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("celerite"); Pkg.test("celerite"; coverage=true)'

matrix:
    include:

	# builds the paper
        - os: linux
          env: TEST_LANG='paper'

install:
    - source .ci/travis.sh

script:
    if [[ $TEST_LANG == paper ]]
    then
        source .ci/build-paper.sh
    fi

# after_success:
#   # push coverage results to Coveralls
#   - julia -e 'cd(Pkg.dir("GenRP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#   # push coverage results to Codecov
#   - julia -e 'cd(Pkg.dir("GenRP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
